<style>
h1.toc {
margin-top: 40px;
margin-bottom: 14px;
}
</style>

<section class="white">
<div class="row">
<div class="col-md-8 col-md-offset-2">

<h1><?= $course->title; ?></h1>
<?php foreach ($course->sections as $section) { ?>
	<h1 class="toc"><a href="<?= $section->lessons[0]->urls['view']; ?>"><?= $section->title; ?></a></h1>

	<?php foreach ($section->lessons as $lesson) { ?>
	<h2 class="toc"><a href="<?= $lesson->urls['view']; ?>"><?= $lesson->title; ?></a></h2>
	<?php }?>
<?php }?>



</div>
</div>
</section>

    <footer class="fooooter">
      <div class="container">
      <div class="row btn-bottom-bar">
       <div class="col-xs-4">
		<a href="#" role="button" class="btn btn-bottom-bar"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
       </div>
       <div class="col-xs-4">
		<a href="#" role="button" class="btn btn-bottom-bar"><span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span></a>       
       </div>
       <div class="col-xs-4">
		<a href="<?= $lesson->urls['toc']; ?>" role="button" class="btn btn-bottom-bar btn-primary"><span class="glyphicon glyphicon-road" aria-hidden="true"></span></a>
       </div>
      
      </div>
      </div>
    </footer>
