<section class="hero">
<div class="row">
<div class="col-md-8 col-md-offset-2">
hero
</div>
</div>
</section>

<section class="white">
<div class="row">
<div class="col-md-8 col-md-offset-2">

<?php
require __DIR__ . '/partial_course-tile.phtml';
foreach($courses as $course) { 
renderCourseTile($course);
}
?>

</div>
</div>
</section>


<section class="gray">
<div class="row">
<div class="col-md-8 col-md-offset-2">
powered by ev3lessons
visit 
</div>
</div>
</section>
