<?php

function renderCourseTile($course) {
	?>
<script>
$(function() {
    $('#course<?= $course->courseId; ?>').click(function() {
		window.location.href = "<?= $course->urls['view']; ?>";
	});
});
</script>
<div class="coursetile" id="course<?= $course->courseId; ?>">
<div><img class="coursetile" src="<?= $course->urls['images']['tile']; ?>"/></div>

<div class="tilecontent">
<h1><a href="<?= $course->urls['view']; ?>"><?= htmlspecialchars($course->title); ?></a></h1>
<!-- <p>By <?= htmlspecialchars($course->user->displayName); ?></p>-->
<p><?= $course->numEnrollments; ?> Enrollments</p>
</div>
</div>
	<?php
}