<h1><?= $user->displayName; ?></h1>
<h2><?= $user->title; ?></h2>
<?php if (isset($user->info->biography)) { ?>
<img src="" alt="<?= $user->displayName; ?>">
<p><?= $user->info->biography; ?></p>

<?php } ?>

<?php if (isset($user->info->links)) { foreach($user->info->links as $key => $link) { ?>
<div><?= $key; ?>: <a href="<?= $link; ?>"><?= $key; ?></a></div>
<?php }} ?>

<h3>Courses authored by <?= $user->displayName; ?></h3>
<?php
require __DIR__ . '/partial_course-tile.phtml';
foreach($courses as $course) { 
renderCourseTile($course);
}
?>

