<section class="hero">

<h1><?= htmlspecialchars($course->title); ?></h1>
<?php if (!is_null($course->subtitle)) { ?> 
	<div><?= $course->subtitle; ?></div>
<?php } ?>

<div class="course-description">
<?= $course->description; ?>
</div>



</section>



<section class="white">

<?php if (!is_null($course->video)) { ?>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<?= json_decode($course->video->content)->videoId; ?>"></iframe>
</div>

<?php } else { ?>
<img src="<?= $course->urls['images']['promo']; ?>" class="img-responsive" alt="<?= $course->title; ?>"/>
<?php } ?>

</section>


<section class="lightgray">
<?php if (count($course->progresses) == 0) { ?>
<div>
<p><a class="btn btn-default" href="<?= $course->urls['enroll']; ?>">Enroll Now</a></p>
<p>Enroll now to save your learning progress.</p>
</div>

<?php } else { 
if (isset($course->progresses[ProgressTypes::CourseFinishedLessonsTotal])) {
	$numFinishedLessons = $course->progresses[ProgressTypes::CourseFinishedLessonsTotal]->value;
} else {
	$numFinishedLessons = 0;
}
if ($course->numLessons > 0) {
	$percent = $numFinishedLessons / $course->numLessons * 100;
} else {
	$percent = 0;
}

?>
<div class="row">
	<div class="col-md-6">
		
	<div style="margin-top: 5px;">
		<div style="float:left; margin: 10px"><?= $numFinishedLessons; ?> of <?= $course->numLessons; ?> lessons complete</div>
		<div class="progress" style="margin: 10px">
		  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?= $numFinishedLessons; ?>"
		  aria-valuemin="0" aria-valuemax="<?= $course->numLessons; ?>" style="width: <?= 
		  $percent;
		  ?>%">&nbsp;
		  </div>
		</div>
	</div>
	</div>
	<div class="col-md-6">
	<div style="margin-top: 5px;">
	<span class="pull-right">
		<a href="<?= $nextLesson->urls['view']; ?>" class="btn btn-default">Start Next Lesson</a>
	</span>
	</div>
	</div>
</div>
<?php } ?>
</section>

<section class="gray">

<h2>Curriculum</h2>

<?php $i=0;
$isRowOpen = false;
foreach($course->sections as $section) {
	$i++;
	$numLessons = count($section->lessons);
	if (isset($section->progresses[ProgressTypes::SectionFinishedLessonsTotal])) {
		$numFinishedLessons = $section->progresses[ProgressTypes::SectionFinishedLessonsTotal]->value;
	} else {
		$numFinishedLessons = 0;
	}
	if ($numLessons > 0) {
		$percent = $numFinishedLessons / $numLessons * 100;
	} else {
		$percent = 0;
	}
	$switch = $i %3 ==0;
	?>

	<?php if (!$isRowOpen) { $isRowOpen = true; ?>
	<div class="row">
	<?php } ?>
	<div class="col-md-4 col-xs-12">
	
		<div class="sectiontile">
		<h1><?= $section->title; ?></h1>
		<div><?= $section->description == '' ? '&nbsp;' : $section->description; ?></div>
		<div class="progress">
		  <div class="progress-bar" role="progressbar" aria-valuenow="<?= $numFinishedLessons; ?>"
		  aria-valuemin="0" aria-valuemax="<?= $numLessons; ?>" style="width:<?= $percent; ?>%">
		  </div>
		</div>

		<?php if (isset($section->progresses[ProgressTypes::SectionFinishedLessonsTotal])) { ?>
        <?= $section->progresses[ProgressTypes::SectionFinishedLessonsTotal]->value; ?> of <?= $numLessons; ?> Lessons finished.
		<a href="<?= $section->urls['nextLesson']; ?>" class="btn btn-default">Continue</a>
		<?php } else { ?>
        <?= $numLessons; ?> Lessons. 
		<a href="<?= $section->urls['nextLesson']; ?>" class="btn btn-default">Start</a>
		<?php } ?>

		</div>
	</div>

	<?php if ($switch && $isRowOpen) { $isRowOpen = false; ?>
	</div>
	<?php } ?>
		
<?php } ?>
<?php if ($isRowOpen) { ?>
</div>
<?php } ?>
</section>

<section class="lightgray">
<p>
<b>Course</b> <a href="<?= $course->urls['view']; ?>" role="button" class="btn btn-default disabled">Overview</a> <a href="<?= $nextLesson->urls['view']; ?>" role="button" class="btn btn-default">Next Lesson</a> <a href="<?= $course->urls['toc']; ?>" role="button" class="btn btn-default">Outline</a>
</p>
</section>