
<script>
$(function() {
	var isLiked = <?= $isLiked ? 1:0?>;
    $('#like').click(function() {
		$.post( "<?= $journey->urls['like']; ?>",
			'',
			function(result) {
				var apiResult = JSON.parse(result);
				toastApiResult(apiResult);
				isLiked = !isLiked;
				if (isLiked) {
					$('#like').switchClass('btn-default', 'btn-primary');
					var num = parseInt($('#numLikes').text()) + 1;
					$('#numLikes').text(num);
				} else {
					$('#like').switchClass('btn-primary', 'btn-default');
					var num = parseInt($('#numLikes').text()) - 1;
					$('#numLikes').text(num);
				}
			}).fail(function(result) {
				toastAjaxResult(result);
			});
	});

	var isChecked = <?= $isChecked ? 1 : 0 ?>;
    $('#check').click(function() {
		$.post( "<?= $journey->urls['check']; ?>",
			'',
			function(result) {
				var apiResult = JSON.parse(result);
				toastApiResult(apiResult);
				isChecked = !isChecked;
				if (isChecked) {
					$('#check').switchClass('btn-default', 'btn-primary');
					var num = parseInt($('#numChecks').text()) + 1;
					$('#numChecks').text(num);
				} else {
					$('#check').switchClass('btn-primary', 'btn-default');
					var num = parseInt($('#numChecks').text()) - 1;
					$('#numChecks').text(num);
				}
			}).fail(function(result) {
				toastAjaxResult(result);
			});
	});


});
</script>

<script>


var app = angular.module('app', []);

app.filter('dateFormat', function() {
    return function(x) {
        return renderDate(x);
    };
});
/**
 * loads further lessons
 */
app.controller('FurtherLessonsCtrl', function($scope, $http){
	
	$http.get('<?= $journey->urls['lessons'] ?>').then(function(response) {
	      $scope.lessons = response.data;
	    });
});

/**
 * handles comments
 */
app.controller('CommentsCtrl', function($scope, $http){
	var commentsUrl = '<?= $journey->urls['comments'] ?>';

	$scope.comment = {};
	$scope.loadComments = function() {
		$http.get(commentsUrl).then(function(response) {
		      $scope.comments = response.data;
		    });
	};
	
    $scope.createComment = function() {
    	$http.post(commentsUrl, $scope.comment)
		  .then(function(data) {
		    $scope.errors = data.data.message.propertyMessages;
	    	toastApiResult(data.data);
	    	$scope.loadComments();
	    	$scope.comment = {};
		  }, function(error) {
		    	toastApiResult(error.data);
		  });
    };

    $scope.loadComments();
});



</script>


<section class="white" ng-app="app">
<h1><?= $journey->title; ?></h1>
<p>Tags: <?= $journey->tags ?></p>
<p><?= $journey->descriptionHtml; ?></p>


<p>Created <?= ViewHelper::renderDate($journey->created); ?> by <a href="#"><?= $journey->user->name; ?></a></p>
<p>
<button class="btn <?= $isLiked ? 'btn-primary' : 'btn-default' ?>" id="like" title="Like this journey"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>&nbsp;
<span id="numLikes"><?= $journey->stats[EntityStats::numLikes]; ?></span>
</button>

<button class="btn <?= $isChecked ? 'btn-primary' : 'btn-default' ?>" id="check" title="Join this journey"><span class="glyphicon glyphicon-check" aria-hidden="true"></span>&nbsp;
<span id="numChecks"><?= $journey->stats[EntityStats::numStationChecks]; ?></span>
</button>
&nbsp;<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp;<?= $journey->stats[EntityStats::numViews]; ?>
&nbsp;<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp;<?= $journey->stats[EntityStats::numComments]; ?>
</p>



<div ng-controller="FurtherLessonsCtrl">

<h2>Stations</h2>

<div class="stationTile" ng-repeat="lesson in lessons">

	<p><a href="{{lesson.urls.view}}"><img ng-src="{{lesson.urls.thumbnail}}" class="stationTile"/></a></p>
	<h3 class="stationTile"><a href="{{lesson.urls.view}}">{{lesson.title}}</a></h3>
	<p class="stationTile">{{lesson.user.displayName}}<br/>{{lesson.numViews}} Views &dash; {{lesson.created | dateFormat}}</p>

</div>
</div>


<div>
<h2>Comments</h2>
<style>

ul.comments {
	list-style-type: none;
	padding: 0px;
}
p.commentCreated {
	color: rgb(124, 124, 124);
}
li.comment {
	margin-bottom: 30px;
}
</style>
<div ng-controller="CommentsCtrl">

<p>Post public comment</p>
<form>
<textarea id="newComment" ng-model="comment.comment"></textarea>
<button id="createComment" ng-click="createComment()" class="btn btn-default">Comment</button>
</form>

<ul class="comments">
	<li class="comment" ng-repeat="comment in comments">
		<p class="commentCreated">{{comment.user.displayName}} - {{comment.created | dateFormat}}</p>
		<p class="comment">{{comment.comment}}</p>
	</li>
</ul>

</div>
</div>

</section>
