
<h1><?= htmlspecialchars($topic->title); ?></h1>

<h2>Sections</h2>
<ul>
<?php foreach($sections as $topic) { ?>
	<li><a href="<?= $topic->url; ?>"><?= htmlspecialchars($topic->title); ?></a></li>

<?php } ?>
</ul>


<h2>Steps</h2>
<ul>
<?php foreach($learningObjects as $learningObject) { ?>
	<li><?= $learningObject->type; ?></li>
	<?php
	
	switch($learningObject->contentStoreType) {
		case ContentStoreTypes::Reference:
		?>
		<object width="100%" height="100%" data="<?= $learningObject->contentReference; ?>"></object>
		<?php
		break;
		case ContentStoreTypes::Embedded:
		echo $learningObject->contentReference;
		break;
	}
	?>
	

<?php } ?>
</ul>

