<section class="hero">
<div class="row">
<div class="col-md-8 col-md-offset-2">

<h1><?= htmlspecialchars($course->title); ?></h1>
<?php if (!is_null($course->subtitle)) { ?> 
	<div><?= $course->subtitle; ?></div>
<?php } ?>

</div>
</div>
</section>



<section class="white">
<div class="row">
<div class="col-md-8 col-md-offset-2">

<div class="row">
<div class="col-md-8">


<?php if (!is_null($course->video)) { ?>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<?= json_decode($course->video->content)->videoId; ?>"></iframe>
</div>

<?php } else { ?>
<img src="<?= $course->urls['images']['promo']; ?>" class="img-responsive" alt="<?= $course->title; ?>"/>
<?php } ?>


</div>
<div class="col-md-4">
<div class="course-description">
<?= $course->description; ?>
</div>



<?php if (count($course->progresses) == 0) { ?>
<div>
<p><a class="btn btn-default" href="<?= $course->urls['enroll']; ?>">Enroll Now</a></p>
<p>Enroll now to save your learning progress.</p>
</div>

<?php } else { 
if (isset($course->progresses[ProgressTypes::CourseFinishedLessonsTotal])) {
	$numFinishedLessons = $course->progresses[ProgressTypes::CourseFinishedLessonsTotal]->value;
} else {
	$numFinishedLessons = 0;
}
if ($course->numLessons > 0) {
	$percent = $numFinishedLessons / $course->numLessons * 100;
} else {
	$percent = 0;
}

?>
<div style="margin-top: 5px;"><a href="<?= $nextLesson->urls['view']; ?>" class="btn btn-default">Start Next Lesson</a></div>
<div style="margin-top: 5px;"><?= $numFinishedLessons; ?> of <?= $course->numLessons; ?> lessons complete
	<div class="progress">
	  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?= $numFinishedLessons; ?>"
	  aria-valuemin="0" aria-valuemax="<?= $course->numLessons; ?>" style="width: <?= 
	  $percent;
	  ?>%">&nbsp;
	  </div>
	</div>
</div>
<?php } ?>

</div>
</div>


</div>
</div>
</section>

<section class="gray">
<div class="row">
<div class="col-md-8 col-md-offset-2">



<h2>Curriculum</h2>

<?php $i=0;
$isRowOpen = false;
foreach($course->sections as $section) {
	$i++;
	$numLessons = count($section->lessons);
	if (isset($section->progresses[ProgressTypes::SectionFinishedLessonsTotal])) {
		$numFinishedLessons = $section->progresses[ProgressTypes::SectionFinishedLessonsTotal]->value;
	} else {
		$numFinishedLessons = 0;
	}
	if ($numLessons > 0) {
		$percent = $numFinishedLessons / $numLessons * 100;
	} else {
		$percent = 0;
	}
	$switch = $i %3 ==0;
	?>

	<?php if (!$isRowOpen) { $isRowOpen = true; ?>
	<div class="row">
	<?php } ?>
	<div class="col-md-4 col-xs-12">
	
		<div class="sectiontile">
		<h1><?= $section->title; ?></h1>
		<div><?= $section->description == '' ? '&nbsp;' : $section->description; ?></div>
		<div class="progress">
		  <div class="progress-bar" role="progressbar" aria-valuenow="<?= $numFinishedLessons; ?>"
		  aria-valuemin="0" aria-valuemax="<?= $numLessons; ?>" style="width:<?= $percent; ?>%">
		  </div>
		</div>

		<?php if (isset($section->progresses[ProgressTypes::SectionFinishedLessonsTotal])) { ?>
        <?= $section->progresses[ProgressTypes::SectionFinishedLessonsTotal]->value; ?> of <?= $numLessons; ?> Lessons finished.
		<a href="<?= $section->urls['nextLesson']; ?>" class="btn btn-default">Continue</a>
		<?php } else { ?>
        <?= $numLessons; ?> Lessons. 
		<a href="<?= $section->urls['nextLesson']; ?>" class="btn btn-default">Start</a>
		<?php } ?>

		</div>
	</div>

	<?php if ($switch && $isRowOpen) { $isRowOpen = false; ?>
	</div>
	<?php } ?>
		
<?php } ?>
<?php if ($isRowOpen) { ?>
</div>
<?php } ?>

</div>
</div>
</section>
