<style>
h1.toc {
margin-top: 40px;
margin-bottom: 14px;
}
</style>

<section class="hero">
<h1><?= $course->title; ?></h1>
</section>
<section class="white">
<?php foreach ($course->sections as $section) { ?>

	<?php if (isset($section->lessons[0])) { ?>
		<h1 class="toc"><a href="<?= $section->lessons[0]->urls['view']; ?>"><?= $section->title; ?></a></h1>
	<?php } else { ?>
		<h1 class="toc"><?= $section->title; ?></h1>
	<?php } ?>
	<?php foreach ($section->lessons as $lesson) { ?>
		<div class="line-item-lesson">
		<img src="<?= $lesson->urls['images']['list']; ?>" alt="<?= $lesson->title; ?>"><a href="<?= $lesson->urls['view']; ?>"><?= $lesson->title; ?></a>
		</div>
	<?php }?>
<?php }?>

</section>
<section class="lightgray">
<p>
<b>Course</b> <a href="<?= $course->urls['view']; ?>" role="button" class="btn btn-default">Overview</a> <a href="<?= $nextLesson->urls['view']; ?>" role="button" class="btn btn-default">Next Lesson</a> <a href="<?= $lesson->urls['toc']; ?>" role="button" class="btn btn-default disabled">Outline</a>
</p>
</section>
