<div class="dialog">
<h1>Choose your new Password</h1>
<p>Hello <?= $user->displayName; ?>,</p>
<p>Please select your new password</p>

<form id="passwordForm">
  <div class="form-group">
	<input type="password" class="form-control" id="newPassword" placeholder="Password">
  </div>
  <button id="submit" type="button" class="btn btn-default">Set new Password</button><br/>
</form>
</div>
<script>
$(function() {
	$('#newPassword').focus()
    $('#submit').click(function() {
		$.post( "<?= $settings['api']; ?>newpassword",
			JSON.stringify({ key: '<?= $passwordKey; ?>', password: $("#newPassword").val() }),
			function(result) {
				var apiResult = JSON.parse(result);

				toastApiResult(apiResult);					
				})
		.fail(function(result) {
			var apiResult = JSON.parse(result);
			toastApiResult(apiResult);
		});
	});
	document.getElementById('newPassword').addEventListener("keydown", function(e) {
		if (!e) {
			var e = window.event;
		}
		if (e.keyCode == 13) {
			$('#login').click();
		}
	}, false);
});
</script>